# Generated by Django 4.1.5 on 2023-01-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('Workstation', 'Workstation'), ('Server', 'Server')], max_length=11),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Ready to deploy', 'Ready to deploy'), ('Deployed', 'Deployed'), ('Pending', 'Pending'), ('Lost/Stolen', 'Lost/Stolen')], max_length=15),
        ),
    ]
