# Generated by Django 4.1.5 on 2023-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_asset_category_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
